### ISSUE TITLE
Feature: support differential update

### ISSUE THREAD

**Issue by zztkm** [zztkm/toolformation#11]
before
```yaml
package-manager: homebrew
homebrew:
    formula:
        - node
        - r
        - pyenv
    cask:
        - visual-studio-code
        - rstudio
        - iterm2
```

```diff
package-manager: homebrew
homebrew:
    formula:
        - node
-       - r
        - pyenv
+       - rust
    cask:
        - visual-studio-code
        - rstudio
        - iterm2
```

## Processing in this case

```
brew uninstall r
brew install rust
```
